services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      # Ngrok key for Expo tunnel
      - EXPO_NGROK_AUTHTOKEN=3CIQI6ZD69GLSt5veG2Nk0MfgZr_6D8ruaVpsU1QsNwK68RRJ
    stdin_open: true
    tty: true